### ISSUE TITLE
Crash report

### ISSUE THREAD

**Issue by Nezumi-chan** [nstlaurent/DoomLauncher#135]
I did not know how else to submit this, so here goes: 

System.NullReferenceException: Object reference not set to an instance of an object.
   at DoomLauncher.UntaggedTabView.SetGameFiles(IEnumerable`1 searchFields)
   at DoomLauncher.MainForm.UpdateLocal()
   at DoomLauncher.MainForm.SyncLocalDatabaseComplete(SyncLibraryHandler handler)
   at DoomLauncher.MainForm.<SyncLocalDatabase>d__48.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at DoomLauncher.MainForm.<WriteDownloadFile>d__197.MoveNext()

**Comment by nstlaurent** [comment]
Thanks for the report, can you explain what you were doing before the crash? This would be helpful for me to reproduce it, thanks.

**Comment by nstlaurent** [comment]
Actually, I was able to figure out how it happened. It has to do with clearing the search before downloading a new file. Will be fixed soon.

**Comment by nstlaurent** [comment]
Fixed on development.
