### ISSUE TITLE
App won't launch.

### ISSUE THREAD

**Issue by The-Albinobigfoot** [nstlaurent/DoomLauncher#180]
Tried to launch on Windows 10 with .NET 4.8 installed. The logo appears briefly before disappearing with no error message of any kind, it simply fails to start.

**Comment by The-Albinobigfoot** [comment]
I tried downloading older versions of the app. Most produced the same result, however, 2.6.1 gave me this error: `System.IO.DirectoryNotFoundException: Unable to save shortcut "C:\Users\Ryan\AppData\Roaming\Microsoft\Windows\SendTo\DoomLauncher.lnk".
   at System.Dynamic.ComRuntimeHelpers.CheckThrowException(Int32 hresult, ExcepInfo& excepInfo, UInt32 argErr, String message)
   at CallSite.Target(Closure , CallSite , ComObject )
   at System.Dynamic.UpdateDelegates.UpdateAndExecute1[T0,TRet](CallSite site, T0 arg0)
   at CallSite.Target(Closure , CallSite , Object )
   at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid1[T0](CallSite site, T0 arg0)
   at DoomLauncher.MainForm.CreateSendToLink()
   at DoomLauncher.MainForm..ctor(String launchFile)
   at DoomLauncher.Program.Main(String[] args)`

**Comment by nstlaurent** [comment]
Thanks for reporting. This shouldn't be happening.

**Comment by nstlaurent** [comment]
This is fixed on development. Doom Launcher will attempt to create the folder if it doesn't exist. If for whatever reason it is not allowed to it watch catch the error and move on instead of crashing.
