### ISSUE TITLE
Unexpected Error when opening exe file.

### ISSUE THREAD

**Issue by Endalus127** [nstlaurent/DoomLauncher#232]
I click the exe and it just pops up with this:

System.UnauthorizedAccessException: Access to the path is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.__Error.WinIOError()
   at System.IO.FileInfo.MoveTo(String destFileName)
   at DoomLauncher.MainForm.InitFileCheck(String initFile, String file, Boolean directory)
   at DoomLauncher.MainForm.VerifyDatabase()
   
I don't know what the issue is. I am the administrator of my computer so I don't know what is wrong.

**Comment by nstlaurent** [comment]
Did you run the installer or unzip from the zip package?

**Comment by Endalus127** [comment]
> 
> 
> Did you run the installer or unzip from the zip package?

I unzipped it from a zip package.

**Comment by nstlaurent** [comment]
It must have been unzipped to a directory it doesn't have permissions to write. You would probably have to right click and select 'Run as administrator'. Otherwise your best bet is to run the installer.
